import type { Metadata } from "next";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import Container from "react-bootstrap/Container";
import  {AppProvider} from '../components/AppContext'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log('root layout')
  return (
    <html lang="en">
      <body>
        <Container>
          <AppProvider>
            {children}
          </AppProvider>
        </Container>
      </body>
    </html>
  );
}
